# This information is pretty specific to my library.  I'll be using it to try to consolidate
# fields that are saying the same thing with different words.
#


field_name_mapping = {
    "creator" : "author", # modified.  It can have multiple authors, just space separated.  Needs to be checked by hand :-(
    "title" : "title",
    "format" : "format",
    "item type" : "item type",
    "no. in series" : "series-index",
    "series" : "series",
    "ISBN" : "isbn", # modified
    "publisher" : "publisher",
    "purchase date" : "purchase date",
    "creation date" : "creation date",
    "release date" : "release date",
    "library of congress" : "library of congress",
    "location" : "location",
    "shelves" : "shelves", # this is a list of shelves (in Library) which show the item.  Comma separated.
 #
    "library of congress" : "library of congress",
    "location" : "location",
    "shelves" : "shelves",
#
    "your image URL" : "cover",
    "amazon link" : "amazon link",
    "amazon product group" : "amazon product group",
    "audience" : "audience",
    "cinematographer" : "cinematographer",
    "composer" : "composer",
    "condition" : "condition", # unused
    "conductor" : "conductor",
    "country" : "country",
    "cover color" : "cover color",
    "current value" : "current value",
    "dewey decimal" : "dewey decimal",
    "EAN" : "EAN",
    "edition" : "edition",
    "features" : "features",
    "genres" : "genres",
    "height" : "height",
    "illustrator" : "illustrator",
    "key" : "key", #unused
    "languages" : "languages",
    "length" : "length",
    "maximum players" : "maximum players",
    "minimum players" : "minimum players",
    "net rating" : "net rating",
    "no. of items" : "no. of items",
    "notes" : "notes",
    "owner" : "owner", # unused
    "pages" : "pages",
    "platform" : "platform",
    "played / read" : "played / read",
    "primary synopsis" : "primary synopsis",
    "private" : "private",
    "purchase price" : "purchase price",
    "rare" : "rare",
    "rating" : "rating",
    "retail price" : "retail price",
    "running time" : "running time",
    "screenwriter" : "screenwriter", # unused
    "serial number" : "serial number",
    "signed" : "signed",
    "stars" : "stars",
    "subtitle" : "subtitle",
    "theatrical debut" : "theatrical debut",
    "tracks" : "tracks",
    "unique item key" : "unique item key",
    "url" : "url", # unused
    "used" : "used",
    "weight" : "weight",
    "width" : "width",
}

media_types = [
    "Music",
    "Book",
    "Toy",
    "Movie",
]

# These all mean pretty much the same thing.
format_audio_cd_set = {
    "Audio CD",
    "CD from UK Import",
    "Audio CD Soundtrack",
    "Audio CD Cast Recording",
    "Audio CD Live",
    "CD audio Bande originale Import",
    "CD",
    "Audio CD Enhanced Original recording remastered",
    "Audio CD Explicit Lyrics Extra tracks",
    "Audio CD Import Live",
    "Audio CD Box set",
    "Audio CD Import",
    "Audio CD Enhanced",
    "Audio CD Explicit Lyrics",
    "Audio CD Import Cast Recording",
    "CD audio Import",
    "Audio CD Original recording remastered",    
}

# These all mean pretty much the same thing.
format_audio_cassette_set = {
    "Audio Cassette Audiobook",
    "Cassette",
    "Audio Cassette",
    "Tape",
    "Casette Tape",
}

formats = [
    "DVD-ROM",
    "DVD",
    "VHS",
    "VHS Tape",
    "Blu-ray",

    "Mass Market Paperback",
    "Mass Market Paperback Illustrated",

    "Perfect Paperback",

    "Paperback Abridged",
    "Paper",
    "Paperback Illustrated",
    "Paperback",
    "Paperbackl",
    "Paperback Box set",
    "Paperback Unabridged",
    "Paperback CD-ROM",
    "Paperback Facsimile",
    "paperback",

    "Trade Paper",
    "Trade Paperback",

    "Black Leather",
    "Leather 4to",
    "Leather Bound",
    "Leatherbound",
    "Leather",

    "Spiral Bound",
    "Spiral-bound",

    "Hardback",
    "Hardbound",
    "Hardcover Abridged",
    "Hardcover Unabridged",
    "Hardcover CD-ROM",
    "Hardcover Illustrated",
    "Hardcover",
    "Clothbound",

    "Library",
    "Library Binding",
    "School & Library Binding",

    "Board book",
    "Board book Unabridged",

    "Textbook Binding",
    "Toy",
    "Kindle Edition",

    "Unbekannter Einband",
    "Map",
    "Software",
    "Turtleback",
    "Plastic Comb",
    "Unknown Binding",
    "Relié",
    "Comic",
    "Broché",
    "Roughcut",
    "Loose Leaf",
    "Poche",
    "Ring Binder",
    "Binder",
    "Magazine",
    "4to",
    "Audio CD Audiobook",
    "Unbound",
    "Photocopy",
    "Cards",
]

series_list = [
    "Classics of Modern Science Fiction",
    "The Executioner",
    "The Mage Winds",
    "The Ashes",
    "The Gates of Time",
    "Daughter of the Lioness",
    "Mack Bolan",
    "The Tales of Alvin Maker",
    "Athens, Greece, November 1-4",
    "Gambler's Star",
    "Prydain Chronicles",
    "Gammalaw",
    "Devil Series",
    "Thieves World Book",
    "Chronicles of the Raven",
    "Thieves World Novel",
    "Southern Vampire Mysteries",
    "Elfquest",
    "Heralds of Valdemar",
    "The Matador Trilogy",
    "Winds of the Forelands",
    "Immortals",
    "Lewis Barnavelt",
    "Horizon War Trilogy",
    "The Paradise War",
    "The Dominions of Irth",
    "The Hardy Boys Mystery Stories",
    "Drenai Tales",
    "The Bhagavad Gita for Living",
    "The Library of America",
    "Young Wizards",
    "Cathy",
    "Changewinds",
    "The Collected Works of C. G. Jung",
    "Chronicles of the Unbinding",
    "Immortal Eyes Trilogy/Jackie Cassada",
    "Kensho",
    "A Novel of the Company",
    "Marvel Graphic Novel",
    "The Monarchies of God",
    "The Chronicles of Counter-Earth",
    "Servants of Ark",
    "Thieves' World",
    "Obernewtyn Chronicles",
    "Sime/Gen",
    "Runespell Trilogy",
    "The Death Merchant",
    "The Godwars",
    "Gil trilogy",
    "Clively Close",
    "The Fleet",
    "The Deed of Paksenarrion",
    "Exiles Saga/Angus Wells",
    "The Tielmaran Chronicles",
    "Guardians Series",
    "The Sun Sword",
    "Destroyer",
    "Alien Trace",
    "Dragonlance Warriors",
    "Michael Sheriff, the Shield",
    "Squire Trilogy",
    "Game Rules, Advanced Fantasy Role Playing, Stock",
    "Mind Masters",
    "Codename",
    "Daw Books Collectors",
    "Keepers of the Hidden Ways",
    "War of the powers",
    "Lensman Series",
    "The Saga of the Seven Suns",
    "The DragonCrown War Cycle",
    "The Taoist Classics: The Collected Translations of Thomas Cleary",
    "Forgotten Realms: The Nobles",
    "The Paratwa Saga",
    "Dumarest of Terra",
    "Mack Bolan the Executioner",
    "Tales of the Timmuras",
    "The Legend Trilogy",
    "Probability and Mathematical Statistics",
    "Pelmen the Powershaper",
    "Feist, Raymond E. Serpent war Saga",
    "The Winter of the World",
    "Mack Bolan Executioner",
    "Defender",
    "Loremasters of Elundium",
    "The Black Magician Trilogy",
    "Finnbrach Trilogy",
    "Rachel Morgan",
    "Sun-Cross",
    "Killmaster",
    "Executioner",
    "The Runespell Trilogy",
    "The Word and the Void Trilogy",
    "Shadowrun",
    "Journeys of the Cathechist",
    "The Cloudmages",
    "Trilogy of the Blood Curse",
    "DARK BORDER",
    "The Stone Dance of the Chameleon",
    "Songkiller Saga",
    "Survivalist",
    "Horseclan",
    "Dushau Trilogy",
    "Evergence",
    "Children of Arable",
    "Spider Trilogy",
    "Chronicles of the King's Tramp",
    "Chosen of the Changeling",
    "Prydain Chronicls",
    "Dune Chronicles",
    "Northworld",
    "Lucky Star",
    "Carolus Rex/Andre Norton",
    "Spellsong Cycle",
    "Tales of the Concordat",
    "Homecoming",
    "The DemonWars Trilogy",
    "The Songkiller Saga",
    "Caithan Crusade",
    "The Pelbar Cycle",
    "Shadowsong Trilogy",
    "Sword of Truth",
    "Myth & Mankind",
    "Io Series",
    "Star Drive Harbinger Trilogy",
    "Starship Troupers",
    "Janus",
    "The Wheel of Time",
    "The Watershed Trilogy",
    "The Lost Continent",
    "The Exploits of Ebenezum",
    "Black Ops",
    "Pleistocene Exile",
    "Otherland",
    "Circle of Light",
    "The History of Middle-Earth",
    "Mack Bolan : Executioner",
    "Witchcraft Today",
    "Dark Border Series",
    "Lost Millennium",
    "Honor Harrington",
    "The Sunset Warrior Sequence",
    "Age of the Five Trilogy",
    "The Swans' War",
    "Psi-Man Series",
    "Hawk & Fisher",
    "The Searchers",
    "Tor Science Fiction",
    "Family d'Alembert Series",
    "Iron Tower Trilogy",
    "Ironfist Chinmi",
    "The Chronicles of Thomas Covenant the Unbeliever",
    "Mack Bolan : the Executioner",
    "The Horizon War",
    "The Jade Demons",
    "The Dresden Files",
    "History of the King of Kantmorie",
    "Martian Tales",
    "Dangerous Journeys",
    "The Shadowleague",
    "Vampire Files",
    "Roderick Alleyn",
    "Time Master Trilogy",
    "A Song of Ice and Fire",
    "Saga of Fafhrd and the Gray Mouser",
    "Cat Series",
    "Soulsmith Trilogy",
    "The Wayfarer Redemption",
    "Adventures of Conrad Stargard/Leo Frankowski",
    "The Obsidian Trilogy",
    "Shadow Warrior",
    "Lucky Starr",
    "Darkwar Triology",
    "Library of America",
    "Super Phoenix Force",
    "Time Wars",
    "The Rigante Series",
    "The Green Lion Trilogy",
    "Riftwar Saga",
    "Bardic Voices",
    "Artemis Fowl",
    "Necroscope Trilogy",
    "Chronicles of Blood and Stone",
    "Mack Bolan, the Executioner",
    "World of Crystal Walls",
    "The Runelords",
    "Images of Garillon / Deborah Harris",
    "Grace & Favor",
    "World at War",
    "Family D'Alembert",
    "Neutronium Alchemist",
    "The Last Legion",
    "The Emancipator",
    "The Eagles",
    "The Story of Civilization",
    "A Man of His Word",
    "Seven Brothers",
    "The World Gates",
    "Diadem",
    "Starfist",
    "Hawk and Fisher",
    "Dragonlance Defenders of Magic",
    "The Star Stone",
    "Mercy Thompson Series",
    "Avaryan Rising",
    "Magick",
    "The Four Lords of the Diamond",
    "The Survivalist",
    "Magicquest",
    "Drums of Chaos/Jo Clayton",
    "Riftwar Legacy/Raymond E. Feist",
    "The Raj Whitehall Series: The General",
    "Winter of the World",
    "Tamuli",
    "Helmsman Series",
    "Swords of Raemllyn",
    "Doc Savage",
    "The Echorium Sequence",
    "Dipple",
    "Diadem Novels",
    "Family D' Alembert",
    "Codex Alera",
    "Rockabilly",
    "Sagamore",
    "The Belgariad",
    "Dread Empire",
    "The Daedalus Mission",
    "Exchameleon",
    "The Malloreon",
    "Voyage of the Basset",
    "Tears of Artamon",
    "Star Shards Trilogy",
    "Tielmaran Chronicles",
    "Demontech",
    "Ninja Master",
    "Memory, Sorrow, and Thorn",
    "Mack Bolan, Superbolan",
    "Earthsea Trilogy",
    "The Wonderland Gambit",
    "Vattu",
    "Collected Lovecraft Fiction",
    "Band of Four",
    "Mack Bolan Executioner Series",
    "Magickers",
    "The Bridge of D'Arnath",
    "Rigante",
    "Flight Over Fire",
    "Lectures in Geometry",
    "Ukiah Oregon",
    "War of Powers",
    "Foxfire",
    "Riftwar Legacy",
    "The Black Company",
    "Infocom",
    "His Dark Materials",
    "Sam Durell",
    "Mutant Chronicles : the Apostle of Insanity Trilogy",
    "Sherlock Holmes",
    "Collected Works of C.G. Jung Vol.9",
    "Wayfarer Redemption",
    "The First Mountain Man",
    "A Bertha Cool and Donald Lam Mystery",
    "The Tamuli",
    "His The Neustrian cycle",
    "Mutants Amok",
    "Seventh Sword",
    "Story of Civilization",
    "Black Oak",
    "The Baroque Cycle",
    "Anthony Monday",
    "The Circle Opens",
    "The Axis Trilogy",
    "The Boreal Moon Tale",
    "The Mage Storms",
    "Astrologer",
    "Nightrunner",
    "The Children of the Red King",
    "Hawk",
    "The Walker Papers",
    "The Last Rune",
    "Feline Wizards",
    "Year of the Ninja Master",
    "Matt Helm",
    "Tales of Alvin Maker/Orson Scott Card",
    "Circle of Magic",
    "Resident Evil",
    "Eternal Champion Series",
    "the Seventh Sword",
    "The Dungeon",
    "Honor Harrington Series",
    "The Ruby Throne Trilogy",
    "the axis trilogy, volume 2",
    "Henry Tibbet",
    "The Lon Tobyn Chronicle",
    "Flight Engineer",
    "Exiles",
    "Adventures of Conrad Starguard",
    "Phoenix Force",
    "The Journeys of Mcgill Feighan",
    "Darkwar Trilogy",
    "Mageworlds",
    "Cryptographic Series",
    "Exordium",
    "Planet Pirates",
    "Starshield",
    "Gamestar Wars",
    "The Banned and the Banished",
    "Tarzan Series",
    "Spellsong Cycle/L.E. Modesitt",
    "Mars",
    "Adventures of Conrad Stargard",
    "Flight Engineer/James Doohan",
    "Harlequin Superromance",
    "Deed of Paksenarrion",
    "Books of Barakhai",
    "The Destroyer",
    "The Secret Texts",
    "Connolly Tarot",
    "A Wizard in Rhyme",
    "The Fifth Foreign Legion",
    "Tale of Krispos",
    "The Rune Blade Trilogy",
    "Destroyer Series",
    "Aliens",
    "The World at War",
    "The Fall of Ile-Rien",
    "WAR OF POWERS",
    "Gammalaw/Brian Daley",
    "Stardoc",
    "The Earthsea Cycle",
    "Casca",
    "Dragonlance Elven Nations",
    "The Fionavar Tapestry",
    "Joe Gall",
    "Mountain Man",
    "Sea King Trilogy",
    "Dark Border",
    "Worldwar Series",
    "The Heritage Universe",
    "Journeys of the Catechist",
    "The Blending Enthroned",
    "The Mechanical Sky",
    "A Handful of Men",
    "Protector of the Small",
    "Doomsday Warrior",
    "Chronicles of Tornor",
    "Ace SF",
    "The Raj Whitehall Series",
    "Phoenix",
    "Pennyfoot Hotel Mystery Series",
    "The Dragon Heart Saga",
    "Gods of Ireland",
    "The Sacred Trilogy",
    "Tielmaran Chronicles/Katya Reiman",
    "The Awakeners",
    "Pellucidar",
    "The Mayflower Trilogy",
    "The Chronicles of Blood and Stone",
    "The Age of Unreason",
    "Serpentwar Saga/Raymond E. Feist",
    "Star of the Guardians",
    "Aquasilva Trilogy",
    "Recluce series",
    "Seven Circles Trilogy",
    "Shapeshifter",
    "Starcruiser Shenandoah",
    "Deathstalker",
    "The Hardy Boys Mystery",
    "Warlord",
    "The Sword of Heaven",
    "The Dominions",
    "A Series of Unfortunate Events",
    "The View from the Mirror",
    "Song of Naga Teot",
    "Super Bolan",
    "Black Throne",
    "Dahak",
    "The Bitterbynde",
    "DragonLance Chronicles",
    "The Chronicles of Magravandias",
    "News from the Edge",
    "The Spiderwick Chronicles",
    "Windrose Chronicles",
    "The Corean Chronicles",
    "Elenium",
    "Spiderwick Chronicles",
    "Schaum's Outline Series",
    "Loeb Classical Library",
    "The Executioner, Mack Bolan",
    "The Dark Tower",
    "Heirs to Gnarlesmyre",
    "Mack Bolan, The Executioner",
    "The Teachings of Don Juan",
    "Dragonlance Chronicles",
    "Arcana/Morgan Llywelyn",
    "Chant",
    "Immortal Eyes",
    "Myth and Mankind",
    "The King's Peace",
    "Blackberets",
    "The Lost Fleet",
    "The Black Berets",
    "The Last Gunfighter",
    "Death Merchant",
    "Cenotaph Road",
    "Pendragon Series",
    "Trilogy",
    "Tamir Trilogy",
    "Seventh Swordsman",
    "Frommer's Hawaii",
    "Stainless Steel Rat",
    "War of the Ninja Master",
    "Mongo",
    "Chronicles of Aelwyn",
    "Everien",
    "The Loregiver Series",
    "NEETS",
    "Oath of Empire",
    "The Dresden Files Series",
    "The Sedona Trilogy",
    "TCP/IP Illustrated",
    "Black Berets",
    "The Vampire Earth",
    "The Duel of Sorcery Trilogy",
    "Dragonriders of Pern",
    "Jade Demons",
    "American Tribal Religions",
    "Blessing Trilogy",
    "The Changes Trilogy",
    "Servants of Ark Trilogy",
    "The Good Cook",
    "The Bhagavad Gita for Daily Living",
    "Daedalus Mission",
    "Requiem for Homo Sapiens",
    "Deathlands",
    "Circle of Magic Series",
    "The Wind on Fire",
    "Studies in Comparative Religion",
    "Conan",
    "Chronicles of Scar",
    "The Hound and the Falcon Trilogy",
    "Foods of the World",
    "Fool's Gold",
    "Wars of Light and Shadow",
    "The Serpentwar Saga",
    "Ace Fantasy Special",
    "Family d'Alembert",
    "Outremer Series",
    "An Anita Blake, Vampire Hunter Novel",
    "Lord of the Isles",
    "Westria",
    "Track",
    "Lensman",
    "High Sierra Hiking Guide",
    "The Book of the Kingdoms",
    "The Hurog Duology",
    "Stormlands",
    "The Vampire Files",
    "The Tale of Krispos",
    "Harlequin Historical",
    "Dumarest",
    "The Farseer Trilogy",
    "The Damned",
    "Dragon's Disciple/Margaret Weis",
    "Song Called Youth",
    "Die Grundlehren Der Mathematischen Wissenschafter",
    "Tarzan",
    "Vampire Earth",
    "Ashton Ford",
    "Colonization",
    "The Sword, the Ring, and the Chalice",
    "Trials of Jernigan",
    "There Will Be War",
    "The Floating Outfit",
    "The Uplift Saga",
    "Star Risk",
    "Forerunner/Shann Lantee",
    "Magical Philosophy",
    "After the Spell Wars Series",
    "Ashes",
    "Sten",
    "The Red Pavilions",
    "Charlie Chan",
    "The Telnarian Histories",
    "Mana",
    "College outline series",
    "Central Control",
    "The Elven Ways",
    "Thieves World",
    "The Defender",
    "Green Rider",
    "The Death Gate Cycle",
    "The Guardians",
    "Horseclans",
    "Sob's, Soldiers of Barrabas",
    "The Destroyer series",
    "Don Pendleton's Executioner Mac Bolan",
    "Watershed Trilogy",
    "Carson of Venus",
    "The Tales of Arthur",
    "Inspector Napoleon Bonaparte",
    "Weather Warden",    
]
